enable: true
botToken: abcdef123456789
chats: []
serverStartMessage: "Server started."
serverStopMessage: "Server stopped."
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logPlayerDeath: true
logPlayerAsleep: false
logPlayerAdvancement: true
logInventory: true
minecraftFormat: "§6§l%username%§r (from §o%chat%§r): §b%message%§r"
telegramFormat: "<i>%username%</i>: %message%"
silentMessages: false
strings:
  online: "<b>Online</b>"
  nobodyOnline: "<b>Nobody online...😔</b>"
  joined: "<i>%username%</i> joined."
  left: "<i>%username%</i> left."
  advancement: "<i>%username%</i> has made the advancement <b>%advancement%</b>.\n(<i>%description%</i>)"
  goal: "<i>%username%</i> has completed the goal <b>%advancement%</b>.\n(<i>%description%</i>)"
  challenge: "<i>%username%</i> has completed the challenge <b>%advancement%</b>.\n(<i>%description%</i>)"
  death: "%deathMessage% 💀"
commands:
  time: "time"
  online: "online"
  chat_id: "chat_id"
