name: PaperTelegramBridge
version: "0.21.0"
api-version: "1.21.4"
main: org.kraftwerk28.spigot_tg_bridge.Plugin
description: Telegram <-> Minecraft communication plugin for Paper/Spigot.
commands:
  tgbridge_reload:
    description: "Reload Spigot TG bridge plugin"
    usage: /<command>
