name: PaperTelegramBridge
version: "0.21.11"
api-version: "1.21.4"
main: eu.pablob.paper_telegram_bridge.Plugin
description: Telegram <-> Minecraft communication plugin for Paper/Spigot.
author: pablo
commands:
  tgbridge_reload:
    description: "Reload paper-telegram-bridge plugin"
    usage: /<command>
permissions:
  tg-bridge.silentjoinleave:
    description: Hide Player from join/leave and online list
    default: false
