name: PaperTelegramBridge
version: "0.21.0"
api-version: "1.21.4"
main: eu.pablob.paper_telegram_bridge.Plugin
description: Telegram <-> Minecraft communication plugin for Paper/Spigot.
commands:
  tgbridge_reload:
    description: "Reload paper-telegram-bridge plugin"
    usage: /<command>
